create table apps (
	id integer primary key generated by default as identity,
	name varchar(250) not null,
	definition jsonb not null,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null,
	deleted boolean not null
);

create table pages (
	id integer primary key generated by default as identity,
	name varchar(250) not null,
	definition jsonb not null,
	app_id integer not null,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null,
	deleted boolean not null,
	constraint fk_pages_apps_app_id foreign key (app_id) references apps(id)
);